[config]
schemaVersion = "0.0.1"

[package]
namespace = "GodModeBoss"
name = "GodModeBoss"
versionNumber = "0.1.1"
description = "Boss Invincible Goto Phase 1/2/3 Change Phase every second"
websiteUrl = "https://github.com/asd9176506911298/NineSols-GodModeBoss"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.4.1"
"ninesolsmodding-BepinExConfigurationManager" = "18.3.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
